### ISSUE TITLE
Instruction how to start recording in README.md

### ISSUE THREAD

**Issue by mikbuch** [edumeet/edumeet-recorder#7]
Please, add the complete instruction on how to run this example to the README?

 1. Build the docker image (already in the README)
 2. Run the image (also in the RAEDME)
 3. Open browser, go to, e.g.: https://letsmeet.no/test-edumeet-recorder
 4. Ask the user(s) to connect to this session

And, what then? In a demo I saw a "recorder" user connected to the session. How to add link for the "recorder" / docker image?

**Comment by mikbuch** [comment]
@kapsa :)

**Comment by mikbuch** [comment]
For example, given that you have an URI: https://letsmeet.no/test-edumeet-recorder

1.  `git clone https://github.com/edumeet/edumeet-recorder.git`
2. `cd edumeet-recorder`
3. `docker build -t edumeet-recorder .`
4. `docker run -v /tmp:/records --rm -it --network=host edumeet-recorder`
5. Open in browser: https://letsmeet.no/test-edumeet-recorder
6. Use curl to start recording:
```
curl
  -i \
  -H "Accept: application/json" \
  -H "Content-Type: application/json" \
    --data '{"type":"uri", \
                 "data":{"encoder":"h264", \
                "bitrate":6000, \
                "uri":"https://letsmeet.no/test-edumeet-recorder?headless=true&displayName=recorder", \
                "stream_uri":"","mode":"record"}}' \
  -X POST http://127.0.0.1:34568/api/start
```
7. Use `curl stop` to stop recording:
```
curl
  -i \
  -H "Accept: application/json" \
  -H "Content-Type: application/json" \
    --data '{"id":1}' \
  -X POST http://127.0.0.1:34568/api/stop
```

Notes:
 * `headless=true` -- no need to stuck on the login/user/landing screen (temporary hack for eduMeet)

**Comment by mikbuch** [comment]
Window 1:
```
➜  edumeet-recorder git:(cef) docker run -v /tmp:/records --rm -it --network=host edumeet-recorder
Listening for requests at: http://localhost:34568/api
```

Window 2:
```
➜  ~ curl \
  -i \
  -H "Accept: application/json" \
  -H "Content-Type: application/json" \
    --data '{"type":"uri", \
                 "data":{"encoder":"h264", \
                "bitrate":6000, \
                "uri":"https://letsmeet.no/test-edumeet-recorder?headless=true&displayName=recorder", \
                "stream_uri":"","mode":"record"}}' \
  -X POST http://127.0.0.1:34568/api/start
curl: (7) Failed to connect to 127.0.0.1 port 34568: Connection refused
➜  ~

**Comment by hevc** [comment]
Do not mix bugs. 

### Describe your issue
<-- a clear and concise summary of the bug. -->

#### Expected Behavior
<-- What did you expect to happen -->

#### Observed Behavior
<-- What actually happened -->

#### Setup
- **Operating System:**
- **Device:** Computer / Tablet / Mobile / Virtual Machine 
- **Docker Version:**
- **Command line:**

### Steps to reproduce the bug
<-- please fill in exact steps which reproduce the bug on your system, for example: -->
1. open terminal
2. type `command`

### How reproducible is the bug?
<-- The reproducibility of the bug is Always/Intermittent/Only once after doing a very specific set of steps-->

### Screenshots if relevant

### Solutions you have tried

### Related non-duplicate issues

### Additional Information
<-- Any other information such as logs. Make use of <details> for long output -->
